services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    # networks:
    #   wg:
    #     ipv4_address: 10.8.0.1
    #     ipv6_address: fdcc:ad94:bacf:61a3::2a
    volumes:
      - /etc/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
    expose:
      - 51821
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
      # - net.ipv6.conf.all.forwarding=1
      # - net.ipv6.conf.default.forwarding=1

# networks:
#   wg:
#     driver: bridge
#     enable_ipv6: true
#     ipam:
#       driver: default
#       config:
#         - subnet: 10.8.0.0/24
#         - subnet: fdcc:ad94:bacf:61a3::/64
